# Perfil de produccion
spring.application.name=cine
server.port=8095
server.servlet.context-path=/api

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.generate-ddl=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=false

jwt.secret=${JWT_SECRET:claveSecretaDelRetoTransversal2DAW2024xYzAbc}
